version: v1.0
name: Python Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: Preinstallation
    task:
      jobs:
        - name: Setup Environment
          commands:
            - sudo apt-get update
            - sudo apt-get install -y libsqlite3-dev git curl nodejs vim yarn build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
            - sudo apt-get install python3.10 python3.10-venv python3.10-dev python3.10-distutils -y
            - python3.10 -m ensurepip --upgrade
            - python3.10 -m pip install --upgrade pip

  - name: Clone Repository and Install Python Dependencies
    task:
      jobs:
        - name: Setup Project
          commands:
            - git clone https://github.com/uroadrun89/SPMB.git /tmp/SPMB
            - cd /tmp/SPMB
            - python3.10 -m venv venv
            - source venv/bin/activate
            - pip install -r requirements.txt

  - name: Run Tests and Main Script
    task:
      jobs:
        - name: Run Tests
          commands:
            - cd /tmp/SPMB
            - source venv/bin/activate
            - python -m unittest discover  # Modify if you have custom test commands

        - name: Run Main Application
          commands:
            - cd /tmp/SPMB
            - source venv/bin/activate
            - python main.py

after_pipeline:
  task:
    jobs:
      - name: Deployment (Optional)
        commands:
          - custom_dns4='1.1.1.1 8.8.8.8'
          - 'sudo sed -i "/\[Resolve\]/a DNS=$custom_dns4" /etc/systemd/resolved.conf'
          - 'sudo curl -s https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh -o /tmp/CFwarp.sh'
          - sudo echo -e "2\n1\n3" > /tmp/input.txt
          - sudo bash /tmp/CFwarp.sh < /tmp/input.txt
