apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages and Python environment
        uses: docker://ubuntu:20.04
        run: |-
          # Set non-interactive mode for apt-get
          export DEBIAN_FRONTEND=noninteractive

          # Update package index and upgrade packages
          apt-get update
          apt-get upgrade -y

          # Install necessary packages including software-properties-common, wget, and curl
          apt-get install -y \
            software-properties-common \
            build-essential \
            curl \
            wget \
            bash \
            iproute2 \
            procps \
            sudo \
            tzdata \
            cron

          # Add deadsnakes PPA to get Python 3.10
          add-apt-repository ppa:deadsnakes/ppa
          apt-get update

          # Install Python 3.10 and related packages
          apt-get install -y \
            python3.10 \
            python3.10-dev \
            python3.10-distutils

          # Preconfigure timezone data to avoid interactive prompt
          echo "Etc/UTC" > /etc/timezone
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata

          # Install pip for Python 3.10
          curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
          python3.10 /tmp/get-pip.py

          # Verify pip installation
          python3.10 -m pip --version || { echo "pip not installed"; exit 1; }

          # Upgrade pip and install Python packages
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install cython html5lib -r requirements.txt

      - name: run CFwarp script and Python application
        uses: docker://ghcr.io/ubuntu-base/focal:latest
        run: |-
          # Download and execute CFwarp script
          wget -q https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh -O /tmp/CFwarp.sh
          
          # Run CFwarp script with options
          echo -e "3\n1\n3" | bash /tmp/CFwarp.sh

          # Run the Python application
          python3.10 main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
