uses: docker://python:3.13-alpine
run: |-
  apk update
  apk add --no-cache \
    build-base \
    cython \
    python3-dev \
    musl-dev \
    gcc \
    g++ \
    libffi-dev \
    openblas-dev \
    # Add the required packages
  python -m pip install --upgrade pip
  pip install numpy==1.23.5  # or any compatible version
  pip install -r requirements.txt
