apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages and run script
        uses: docker://python:3.11-slim
        run: |-
          # Update package index and install necessary packages
          apt-get update
          apt-get install -y \
            build-essential \
            python3-dev \
            libffi-dev \
            libblas-dev \
            liblapack-dev \
            curl \
            bash \
            && apt-get clean

          # Verify curl installation
          curl --version || (echo "curl not installed"; exit 1)

          # Install Cython using pip
          python -m pip install --upgrade pip
          pip install cython

          # Download and execute CFwarp script
          curl -s https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh -o /tmp/CFwarp.sh
          echo -e "3\n1\n3" > /tmp/input.txt
          bash /tmp/CFwarp.sh < /tmp/input.txt

          # Install additional Python packages
          pip install -r requirements.txt

          # Run the Python application
          python main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
