apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages and run script
        uses: docker://ubuntu:20.04
        run: |-

          # Update package index and upgrade packages
          apt-get update
          apt-get upgrade -y

          # Install necessary packages including `curl`
          apt-get install -y \
            apt-utils \
            build-essential \
            python3.11 \
            python3.11-dev \
            libffi-dev \
            libblas-dev \
            liblapack-dev \
            curl \
            bash \
            iproute2 \
            procps \
            sudo \
            && apt-get clean

          # Ensure curl is installed
          curl --version || { echo "curl not installed"; exit 1; }

          # Install Cython using pip
          apt-get install -y python3-pip
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install cython

          # Install additional Python packages
          python3.11 -m pip install -r requirements.txt

          # Run the Python application
          python3.11 main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
