apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      
      - name: install packages
        uses: docker://python:3.13.0-buster
        run: |-
          # Update package index and install necessary packages
          apt-get update
          apt-get install -y \
            build-essential \
            cython3 \
            python3-dev \
            libffi-dev \
            libblas-dev \
            liblapack-dev \
            gfortran

          # Upgrade pip and install Python packages
          python -m pip install --upgr
