apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages
        uses: docker://python:3.11-alpine
        run: |-
          # Update package index and install necessary packages
          apk update
          apk add --no-cache \
            build-base \
            cython \
            python3-dev \
            musl-dev \
            gcc \
            g++ \
            libffi-dev \
            openblas-dev \
            lapack-dev \
            py3-pip

          # Upgrade pip and install Python packages
          python -m pip install --upgrade pip

          # Install additional Python packages
          pip install -r requirements.txt

      - name: prepare environment
        uses: docker://python:3.11-alpine
        run: |-
          # Ensure /tmp has the right permissions
          chmod 1777 /tmp

          # Create a directory to hold your application
          mkdir -p /tmp/app

          # Copy application files to /tmp/app
          cp -r /cloudbees/workspace/* /tmp/app || { echo "Failed to copy files to /tmp/app"; exit 1; }

          # Verify that files are copied and directory exists
          if [ ! -d "/tmp/app" ]; then
            echo "/tmp/app directory does not exist. Exiting."
            exit 1
          fi

          if [ -z "$(ls -A /tmp/app)" ]; then
            echo "/tmp/app directory is empty. Exiting."
            exit 1
          fi

      - name: run application
        uses: docker://python:3.11-alpine
        run: |-
          # Verify that /tmp/app exists and is not empty before running the script
          if [ -d "/tmp/app" ] && [ "$(ls -A /tmp/app)" ]; then
            cd /tmp/app || { echo "Failed to change directory to /tmp/app"; exit 1; }

            # Run the Python application
            python main.py || { echo "Python script execution failed"; exit 1; }
          else
            echo "/tmp/app directory does not exist or is empty. Exiting."
            exit 1
          fi

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
