apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages
        uses: docker://python:3.11-alpine
        run: |-
          # Update package index and install necessary packages
          apk update
          apk add --no-cache \
            build-base \
            cython \
            python3-dev \
            musl-dev \
            gcc \
            g++ \
            libffi-dev \
            openblas-dev \
            lapack-dev \
            py3-pip

          # Upgrade pip and install Python packages
          python -m pip install --upgrade pip

          # Install additional Python packages
          pip install -r requirements.txt

      - name: prepare environment
        uses: docker://python:3.11-alpine
        run: |-
          # Ensure /tmp has the right permissions
          chmod 1777 /tmp
          
          # Create a directory to hold your application
          mkdir -p /tmp/app

          # Copy application files to /tmp/app
          cp -r /cloudbees/workspace/* /tmp/app

          # Change to the application directory
          cd /tmp/app

      - name: run application
        uses: docker://python:3.11-alpine
        run: |-
          # Change to the application directory
          cd /tmp/app

          # Run the Python application
          python main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
