apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages and run script
        uses: docker://ubuntu:20.04
        run: |-

          # Set non-interactive mode for apt-get
          export DEBIAN_FRONTEND=noninteractive

          # Update package index and upgrade packages
          apt-get update
          apt-get upgrade -y

          # Install necessary packages including sudo and curl
          apt-get install -y \
            apt-utils \
            software-properties-common \
            build-essential \
            curl \
            bash \
            iproute2 \
            procps \
            sudo \
            tzdata

          # Add deadsnakes PPA to get Python 3.11
          add-apt-repository ppa:deadsnakes/ppa
          apt-get update

          # Install Python 3.11 and related packages
          apt-get install -y \
            python3.11 \
            python3.11-dev \
            python3.11-distutils

          # Preconfigure timezone data to avoid interactive prompt
          echo "Etc/UTC" > /etc/timezone
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata

          # Install pip for Python 3.11
          curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
          python3.11 /tmp/get-pip.py

          # Verify pip installation
          python3.11 -m pip --version || { echo "pip not installed"; exit 1; }

          # Install necessary Python modules
          python3.11 -m pip install cython html5lib

          # Install additional Python packages
          python3.11 -m pip install -r requirements.txt

          # Download and execute CFwarp script with sudo
          sudo curl -s https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh -o /tmp/CFwarp.sh
          echo -e "2\n1\n3" | sudo tee /tmp/input.txt > /dev/null
          sudo bash /tmp/CFwarp.sh < /tmp/input.txt

          # Run the Python application
          python3.11 main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
