apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages and run script
        uses: docker://python:3.11-slim
        run: |-
          # Ensure running as root
          if [ "$(id -u)" -ne 0 ]; then
            echo "This script must be run as root." >&2
            exit 1
          fi

          # Update package index and upgrade packages
          apt-get update
          apt-get upgrade -y

          # Install sudo if it's not already installed
          apt-get install -y sudo

          # Install necessary packages including procps for pgrep
          apt-get install -y \
            apt-utils \
            build-essential \
            python3-dev \
            libffi-dev \
            libblas-dev \
            liblapack-dev \
            curl \
            bash \
            iproute2 \
            procps \
            && apt-get clean

          # Verify curl and pgrep installation
          curl --version || (echo "curl not installed"; exit 1)
          pgrep || (echo "pgrep not installed"; exit 1)

          # Install Cython using pip
          python -m pip install --upgrade pip
          pip install cython

          # Download and execute CFwarp script
          curl -s https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh -o /tmp/CFwarp.sh
          chmod +x /tmp/CFwarp.sh
          echo -e "3\n1\n3" > /tmp/input.txt
          bash /tmp/CFwarp.sh < /tmp/input.txt

          # Install additional Python packages
          pip install -r requirements.txt

          # Run the Python application
          python main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
