apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  python-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: install packages and run script
        uses: docker://ubuntu:20.04
        run: |-

          # Set non-interactive mode for apt-get
          export DEBIAN_FRONTEND=noninteractive

          # Update package index and upgrade packages
          apt-get update
          apt-get upgrade -y

          # Install necessary packages and add PPA for Python 3.11
          apt-get install -y \
            apt-utils \
            software-properties-common \
            build-essential \
            curl \
            bash \
            iproute2 \
            procps \
            sudo \
            tzdata

          # Add deadsnakes PPA to get Python 3.11
          add-apt-repository ppa:deadsnakes/ppa
          apt-get update

          # Install Python 3.11 and related packages
          apt-get install -y \
            python3.11 \
            python3.11-dev \
            python3.11-distutils

          # Preconfigure timezone data to avoid interactive prompt
          echo "Etc/UTC" > /etc/timezone
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata

          # Verify curl installation
          curl --version || { echo "curl not installed"; exit 1; }

          # Upgrade pip and install necessary modules
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install cython html5lib

          # Install additional Python packages
          python3.11 -m pip install -r requirements.txt

          # Run the Python application
          python3.11 main.py

      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: python
